### PR TITLE
Add Prism Xamarin.Forms Full App template.

### PR DESCRIPTION
**Pull request by bakerhillpins**
I converted the WPF project to Xamarin.Forms so I figured I'd add it as a template.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/PrismLibrary/Prism.Templates?pullRequest=42) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/PrismLibrary/Prism.Templates?pullRequest=42) before we can accept your contribution.<br/><br/>:x: bakerhillpins [sign now](https://cla.dotnetfoundation.org/PrismLibrary/Prism.Templates?pullRequest=42)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/PrismLibrary/Prism.Templates?pullRequest=42) it.</sub>

**Comment by bakerhillpins** [comment]
For [this issue](https://github.com/PrismLibrary/Prism.Templates/issues/41).

**Comment by bakerhillpins** [comment]
I'm willing to try to deal with a few other issues in the PR as well, assuming that's the way you'd like to handle it. Otherwise I could branch off and do them individually after I've gone through the process here once.

**Comment by dansiegel** [comment]
Thank you for the PR. At this time @brianlagunas and I have decided that this is not something that we're going to be adding. Xamarin.Forms itself is in maintenance mode and only receiving patches before reaching End of Life. Our efforts are not well spent investing much capital in Xamarin.Forms at this time as we are putting our efforts towards Maui. 
It is also important to note that the addition of a template here still requires time to integrate into the Visual Studio extension which is not likely to happen for quite some time.

**Pull request closed without merging**
